import type { SportProfile } from './types.js'

const BASE_CHECKLIST = [
  'Production PC connected',
  'OBS connected',
  'All cameras online',
  'Network online',
  'Graphics package installed',
  'Graphics server online',
  'Scoreboard configured',
  'Audio tested',
  'Intercom tested',
  'Replay tested',
  'Stream destination configured',
  'Recording enabled',
  'Backup recording enabled',
]

const common = {
  clockCountsDown: true,
  replay: { durations: [5, 10, 15], defaultDuration: 10, defaultSpeed: 50, returnToLive: true },
  checklist: BASE_CHECKLIST,
}

/** Seed profiles. Written to the database on first run and editable from Settings afterwards. */
export const DEFAULT_SPORTS: SportProfile[] = [
  {
    ...common,
    id: 'basketball',
    name: 'Basketball',
    periodLabel: 'Quarter',
    periods: ['Q1', 'Q2', 'Q3', 'Q4', 'OT'],
    defaultTimeouts: 5,
    fields: ['homeScore', 'awayScore', 'period', 'clock', 'shotClock', 'homeFouls', 'awayFouls', 'homeTimeouts', 'awayTimeouts', 'possession'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'startingLineup', 'coach', 'sponsor', 'halftime', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'football',
    name: 'Football',
    periodLabel: 'Quarter',
    periods: ['Q1', 'Q2', 'Q3', 'Q4', 'OT'],
    defaultTimeouts: 3,
    fields: ['homeScore', 'awayScore', 'period', 'clock', 'down', 'distance', 'ballOn', 'possession', 'homeTimeouts', 'awayTimeouts'],
    graphics: ['scoreboard', 'firstDown', 'touchdown', 'lowerThird', 'playerIntro', 'startingLineup', 'coach', 'sponsor', 'halftime', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'volleyball',
    name: 'Volleyball',
    periodLabel: 'Set',
    periods: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
    clockCountsDown: false,
    defaultTimeouts: 2,
    fields: ['homeScore', 'awayScore', 'period', 'homeTimeouts', 'awayTimeouts', 'possession'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'startingLineup', 'coach', 'sponsor', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'soccer',
    name: 'Soccer',
    periodLabel: 'Half',
    periods: ['1st Half', '2nd Half', 'ET1', 'ET2'],
    clockCountsDown: false,
    defaultTimeouts: 0,
    fields: ['homeScore', 'awayScore', 'period', 'clock'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'startingLineup', 'coach', 'sponsor', 'halftime', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'baseball',
    name: 'Baseball',
    periodLabel: 'Inning',
    periods: ['T1', 'B1', 'T2', 'B2', 'T3', 'B3', 'T4', 'B4', 'T5', 'B5', 'T6', 'B6', 'T7', 'B7', 'T8', 'B8', 'T9', 'B9'],
    clockCountsDown: false,
    defaultTimeouts: 0,
    fields: ['homeScore', 'awayScore', 'period'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'startingLineup', 'coach', 'sponsor', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'softball',
    name: 'Softball',
    periodLabel: 'Inning',
    periods: ['T1', 'B1', 'T2', 'B2', 'T3', 'B3', 'T4', 'B4', 'T5', 'B5', 'T6', 'B6', 'T7', 'B7'],
    clockCountsDown: false,
    defaultTimeouts: 0,
    fields: ['homeScore', 'awayScore', 'period'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'startingLineup', 'coach', 'sponsor', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'wrestling',
    name: 'Wrestling',
    periodLabel: 'Period',
    periods: ['P1', 'P2', 'P3', 'OT'],
    defaultTimeouts: 0,
    fields: ['homeScore', 'awayScore', 'period', 'clock'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'coach', 'sponsor', 'final', 'fullscreen'],
  },
  {
    ...common,
    id: 'generic',
    name: 'Generic',
    periodLabel: 'Period',
    periods: ['P1', 'P2', 'P3', 'P4'],
    defaultTimeouts: 3,
    fields: ['homeScore', 'awayScore', 'period', 'clock', 'possession'],
    graphics: ['scoreboard', 'lowerThird', 'playerIntro', 'sponsor', 'fullscreen'],
  },
]

/** Field labels for the scoreboard page. */
export const FIELD_LABELS: Record<string, string> = {
  homeScore: 'Home Score',
  awayScore: 'Away Score',
  period: 'Period',
  clock: 'Clock',
  shotClock: 'Shot Clock',
  homeFouls: 'Home Fouls',
  awayFouls: 'Away Fouls',
  homeTimeouts: 'Home Timeouts',
  awayTimeouts: 'Away Timeouts',
  possession: 'Possession',
  down: 'Down',
  distance: 'Distance',
  ballOn: 'Ball On',
}
